site_name: ドキュメント！！！

theme:
  name: "material"
  palette:
    primary: orange
    accent: otange

plugins:
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                rendering:
                    show_source: false  
        watch:
            - src/fox
